### ISSUE TITLE
Novelty Tagm ToDo

### ISSUE THREAD

**Issue by ococrook** [lgatto/pRoloc#127]
In Novelty-Tagm Branch:
- [ ] Code review current Tagm Novelty functions (L)
- [ ] Code review current Tagm Novelty classes (L) (add show?)
- [ ] Update Description file (O)
- [ ] Update Read Me (O)
- [ ] Add unit tests (O)
- [ ] Add vignette (O)
