### ISSUE TITLE
marker vectors and matrices

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRoloc#52]
Functions to convert vector to/from matrix markers and show the matrix markers.
### TODO
- [x] ~~Update `plot2D`so that is works for Markers.~~ 
- [x] Add `plotMat2D` (using shiny) to `pRolocGUI`. 
- [x] Update `getMarkers` so that is works for Markers.
- [x] Update `getMarkerClasses`so that is works for Markers.
- [x] Update `markerMSnSet`so that is works for Markers.
- [x] Update `unkownMSnSet`so that is works for Markers.
- [ ] Update `testMSnSet`so that is works for Markers.
- [x] Update `sampleMSnSet`so that is works for Markers.
- [x] combine the documentation for marker-related functions, such as `getMarkers` and `getMarkerClasses` and probably others - see below. 
- [x] `?markers` should be an alias for the main man page that describes markers. 

See also issue #55 for a broader discussion.

**Comment by lgatto** [comment]
A list of marker-related functions:
```
markerMSnSet
unknownMSnSet
getMarkers
getMarkerClasses
testMarkers
minMarkers
addMarkers
pRolocmarkers
mrkVecToMat
mrkMatToVec
mrkMatAndVec
showMrkMat
```
